### ISSUE TITLE
No report shown when pressing the button

### ISSUE THREAD

**Issue by oparoz** [nextcloud/survey_client#15]
### Steps to reproduce

1. Read the doc
1. Press the button

### Expected behaviour

I should get a message on screen showing to me what was sent to the server, as promised

### Actual behaviour

Nothing (in apparance)
I can see the request in the browser debug tool and see that the data is sent back to the browser

There is nothing in the logs, so maybe the feature which shows the data isn't implemented yet, but if that's the case this text shozld be altered:

>We take your privacy seriously. The data are anonymized and you can enable/disable it at any time, by default it is always disabled. Below you can also adjust what kind of data are send and always see the last report send to us.

**Comment by blizzz** [comment]
The corresponding form fields are only added to the HTML output, if there is a last report. Does not work the very first time, obviously. On a fix.
