### ISSUE TITLE
Provide a prefilled issue template

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/survey_client#27]
Would be nice to have a downloadable file, which shows all of the questions asked in the issue template on `nextcloud/server` prefilled with informations like enabled apps, php version, configuration, ... This would make it easier for admins to fill out the issue template 😉 

cc @nickvergessen @schiessle

**Comment by nickvergessen** [comment]
@LukasReschke is your app still a thing? :stuck_out_tongue_winking_eye:

**Comment by mar1u5** [comment]
I think @juliushaertl has solved this 😅👍 
https://github.com/juliushaertl/issuetemplate
