### ISSUE TITLE
Needs a proper icon

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/survey_client#33]
This was already discussed heavily in https://github.com/nextcloud/server/issues/856

@Bugsbane and @eppfel had already nice ideas.

@eppfel Did you finished the icon already?

**Comment by eppfel** [comment]
Nope, tried 1-2 ideas. Wasn't satisfied, yet. But we'll finish it at the conference ;)

**Comment by MorrisJobke** [comment]
> Nope, tried 1-2 ideas. Wasn't satisfied, yet. But we'll finish it at the conference ;)

Ah :) Thanks :)

**Comment by Bugsbane** [comment]
It seems that I didn't really get what the app does, as I thought it was something to do with getting users to fill out a survey, which seems to be inaccurate. I'd be interested in revisiting this if someone could just provide a 1-2 sentence description of what the app actually does. :)

**Comment by MorrisJobke** [comment]
> It seems that I didn't really get what the app does, as I thought it was something to do with getting users to fill out a survey, which seems to be inaccurate. I'd be interested in revisiting this if someone could just provide a 1-2 sentence description of what the app actually does. :)

The app actually does send usage stats (PHP version, used configuration like enabled apps, enabled config switches, etc., available shares count by type, available files count, user count, ...) to a server that is on our side. So we have a rough overview of what is actually used and what not.

It's called survey because it is a kind of automated survey from the instances itself and is opt-in. So the admin gets a notification and needs to accept that those information are send ;)

**Comment by Bugsbane** [comment]
Ah, Ok. So it's more an automated usage stats app. Cool. Thanks @MorrisJobke

**Comment by MorrisJobke** [comment]
ping @jancborchardt

**Comment by MorrisJobke** [comment]
@eppfel or do you have any news here?

**Comment by eppfel** [comment]
nope, something like these work?
https://thenounproject.com/search/?q=report&i=794733
https://thenounproject.com/search/?q=report&i=794736
https://thenounproject.com/term/statistic/

**Comment by MorrisJobke** [comment]
> https://thenounproject.com/search/?q=report&i=794736

I like this one most.

**Comment by eppfel** [comment]
mh, something like this? I feel the border is too thin...

![usage_report 3x](https://cloud.githubusercontent.com/assets/1899308/22106058/45e20830-de47-11e6-9a14-c025677a48d4.png)
![usage_report](https://cloud.githubusercontent.com/assets/1899308/22106088/582343f6-de47-11e6-8ea5-0c1a7ea63e5b.png)

```XML
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="100%" height="100%" viewBox="0 0 16 16" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:1.5;">
    <path d="M10.506,1.654l1.873,0c0.609,0 1.103,0.494 1.103,1.103l0,10.702c0,0.608 -0.494,1.103 -1.103,1.103l-8.758,0c-0.609,0 -1.103,-0.495 -1.103,-1.103l0,-10.702c0,-0.609 0.494,-1.103 1.103,-1.103l1.873,0" style="fill:none;stroke:#000;stroke-width:0.8px;" />
    <path d="M10.506,0.895l-5.012,0l0,1.522c0,0.28 0.227,0.507 0.507,0.507l3.998,0c0.28,0 0.507,-0.227 0.507,-0.507l0,-1.522Z" style="fill:none;stroke:#000;stroke-width:0.8px;stroke-linejoin:miter;" />
    <g>
        <rect x="7" y="8.998" width="1.999" height="4" />
        <rect x="9.999" y="6.982" width="1.999" height="6.016" />
        <rect x="4.001" y="10.989" width="1.999" height="2.009" />
    </g>
</svg>
```

**Comment by nickvergessen** [comment]
Looks good

**Comment by MorrisJobke** [comment]
Looks really nice:

![bildschirmfoto 2017-01-19 um 12 45 05](https://cloud.githubusercontent.com/assets/245432/22120393/2311de4a-de45-11e6-9fb6-9987450b6d1c.png)

I optimized the code a bit and it now looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="16" height="16" clip-rule="evenodd" fill-rule="evenodd" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="1.5" version="1.1" viewBox="0 0 16 16" xml:space="preserve" xmlns="http://www.w3.org/2000/svg">
    <path d="m10.506 1.654h1.873c0.609 0 1.103 0.494 1.103 1.103v10.702c0 0.608-0.494 1.103-1.103 1.103h-8.758c-0.609 0-1.103-0.495-1.103-1.103v-10.702c0-0.609 0.494-1.103 1.103-1.103h1.873" fill="none" stroke="#fff" stroke-width=".8px"/>
    <path d="m10.506 0.895h-5.012v1.522c0 0.28 0.227 0.507 0.507 0.507h3.998c0.28 0 0.507-0.227 0.507-0.507v-1.522z" fill="none" stroke="#fff" stroke-linejoin="miter" stroke-width=".8px"/>
        <rect x="7" y="8.998" width="1.999" height="4" fill="#fff" />
        <rect x="9.999" y="6.982" width="1.999" height="6.016" fill="#fff" />
        <rect x="4.001" y="10.989" width="1.999" height="2.009" fill="#fff" />
</svg>
```
