### ISSUE TITLE
 Frequent “No App in Context” Errors in LOG on newly installed NC 10 

### ISSUE THREAD

**Issue by githubos1** [nextcloud/survey_client#36]
### Steps to reproduce
1. new "raw" install of NC 10
2. as soon as Admin logs in and uses Admin panel, Errors are beeing logged
3.

### Expected behaviour
NOTHING... no errors

### Actual behaviour
following errors beeing logged:
{"reqId":"V@UPo1UNiDMAAEhnMZUAAAAK","remoteAddr":"91.52.xx.yy","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\Survey_Client\\\\Settings\\\\AdminSection! Class OCA\\\\Survey_Client\\\\Settings\\\\AdminSection does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(105): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Survey_Clie...')\\n#1 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/private\\\/ServerContainer.php(89): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Survey_Clie...')\\n#2 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/private\\\/Settings\\\/Manager.php(319): OC\\\\ServerContainer->query('OCA\\\\\\\\Survey_Clie...')\\n#3 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/private\\\/Settings\\\/Manager.php(354): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\Survey_Clie...')\\n#4 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/settings\\\/Controller\\\/AdminSettingsController.php(131): OC\\\\Settings\\\\Manager->getAdminSections()\\n#5 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/settings\\\/Controller\\\/AdminSettingsController.php(70): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getNavigationParameters('server')\\n#6 [internal function]: OC\\\\Settings\\\\Controller\\\\AdminSettingsController->index('server')\\n#7 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#8 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#9 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/private\\\/AppFramework\\\/App.php(111): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#10 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('AdminSettingsCo...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/private\\\/Route\\\/Router.php(293): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/base.php(967): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#14 \\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/index.php(48): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/_ALL-INKL_\\\/_myclouddir_\\\/nextcloud10test\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":90}","level":3,"time":"2016-09-23T11:19:00+00:00","method":"GET","url":"\/index.php\/settings\/admin","user":"admin"}

### Server configuration

    Hosted Server ALL-INKL /mySQL Database ver5.5.50
    php 7.0.10

    access via Let'sEncrypt SSL

    remoteAddr in LOG = my accessing home ip
-  No client installed
-  ONE testuser created... plus ADMIN
-  no files uploaded (raw install)
-  ownpad APP installed and running successfully but error happens if enabled or disabled
-  two testfiles successfully created via ownpad APP later deleted...
-   additional apps added: CALENDAR, CONTACTS, DOCUMENTS, TASKS, ownpad

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
all standard apps PLUS:
CALENDAR, CONTACTS, DOCUMENTS, TASKS, ownpad

"USAGE Report" was not enabled !!

NOW, It seems that the errors reported only get generated when the app "USAGE Report"  is disabled (STRANGE behaviour !!!) as it was in my case... and even same behaviour when I deleted the whole app from the apps directory. So I guess something must be calling this app/script even when it's not there or disabled.

Once I enabled the app, and unticked all possible reports (as I did not want to send usage data) in admin settings, the error logging stopped...

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocv8vo148uy8',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'test10.netdav.de',
  ),
  'datadirectory' => '/www/htdocs/w005850c/-DATA/TESTCLOUD/data',
  'tempdirectory' => '/www/htdocs/w005850c/-DATA/_testcloudtemp',
  'overwrite.cli.url' => 'http://test10.netdav.de',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  #'appstoreenabled' => true,
  #'appstoreurl' => 'https://api.owncloud.com',
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
This will be fixed with 10.0.1 already i think.
Might be, that you need to reenable and disable the app again

**Comment by githubos1** [comment]
As soon as I disable the app (did this twice disable, enable, disable)  errors start beeing logged...

**Comment by nickvergessen** [comment]
Yes, but you dont have 10.0.1 yet either

**Comment by githubos1** [comment]
yep, right, sorry misunderstanding  ;-)  thought you meant -enabling & disabling to solve the errors on current 10.0 version..
