### ISSUE TITLE
Disabling survey client violates your privacy by forcing you to send data to disable it

### ISSUE THREAD

**Issue by GiantCrocodile** [nextcloud/survey_client#67]
I would like to see this improved. I refer to this short topic in forum: https://help.nextcloud.com/t/does-disabing-the-survey-option-force-you-to-send-data-to-external-servers/21271

**Comment by nickvergessen** [comment]
what?! No! You seem to misunderstand this a bit. Checking or unchecking any of the check boxes does NOT send a report. Only the "Send new report now" button sends a report.

Also please note the second sentence in the description:
> We take your privacy seriously. Sending data is disabled by default, …

So when no report was ever sent, you can just uncheck all the boxes and then additionally disable the "Usage survey" app in the app management to be on the save side.

When a report was submitted before, just uncheck all the boxes and "Send new report now" before disabling the app, and all data will be wiped from our servers

**Comment by GiantCrocodile** [comment]
This makes sense @nickvergessen but it seems the German translation does tell you something different:
```
Wenn Du eine der unteren Einstellungen deaktivierst, dann wird ein neuer Bericht gesendet und alle bisher bei Nextcloud gespeicherten Daten gelöscht. 
```

This means what I wrote above. It looks like you are right but the translation has been done misleading.

**Comment by nickvergessen** [comment]
Ah right, I fixed the translation now:
> Wenn Du eine der unteren Einstellungen deaktivierst, sende einen neuen Bericht um alle bisher bei Nextcloud gespeicherten Daten zu löschen.
